### ISSUE TITLE
how to pull from command line with auth credentials for package download

### ISSUE THREAD

**Issue by gebele** [num-codex/odm2fhir#1]
Bitte in die package Beschreibung eintragen wie man downloaden kann.
```
$ cat ~/TOKEN.txt | docker login https://docker.pkg.github.com -u USERNAME --password-stdin
```
und im personal access token muss noch der Haken bei `read:packages` gesetzt werden !

**Comment by holger-stenzhorn** [comment]
Added link to the respective documentation with in the description.
