### ISSUE TITLE
Referencing of Patients seems to be inconsistent

### ISSUE THREAD

**Issue by sebmate** [num-codex/odm2fhir#11]
Hi,

I'm working on an ETL job that imports the odm2fhr-generated GECCO FHIR into i2b2. I noticed some inconsistencies in the generated resources in the way the patient is referenced:

Most common way (and probably the correct one):

```
subject->reference
```
In the Immunization resource I noticed a difference:
```
patient->reference
```
as well as:
```
patient->identifier->value
```
I think that the third way of referencing the patient in Immunization is from an older version of odm2fhir and was attempted to be fixed in the second one, which is still incorrect. Unfortunately I don't know which version of odm2fhir was used by my colleague when he generated the files. Referencing types 2 and 3 are from two different data exports.

Best, Sebastian

**Comment by cerbelding** [comment]
Hi @sebmate,
the Immunization ressource (as defined [here](https://simplifier.net/guide/GermanCoronaConsensusDataSet-ImplementationGuide/Immunizationstatus)), as well as the Consent resource, differ in the way the Subject is referenced compared to all other resources.

In these two profiles, the subject is referenced as `patient`->`reference` with `reference`->`identifier`->`value` (value = Patient/1234567)

**Comment by sebmate** [comment]
Hi @cerbelding , thanks for your quick reply!
