### ISSUE TITLE
Field resource.identifier does not have system

### ISSUE THREAD

**Issue by makampf** [num-codex/odm2fhir#15]
**Describe the bug**
The field system is missing in resource.identifier. Only the value is given.

**To Reproduce**
Export resource (e.g. Patient) with odm2fhir

**Expected behavior**
The resource.identifier should have system and value. (and maybe also type). Even if it is optional.

**Example**
From https://simplifier.net/guide/GermanCoronaConsensusDataSet-ImplementationGuide/TransactionBundle
```json
"identifier":  [
  {
      "type": {
          "coding":  [
              {
                  "system": "http://terminology.hl7.org/CodeSystem/v2-0203",
                  "code": "MR"
              }
          ]
      },
      "system": "https://www.charite.de/fhir/CodeSystem/medical-record-numbers",
      "value": "43814872",
      "assigner": {
          "reference": "Organization/Charité"
      }
  }
]
```

Note: please also consider issue https://github.com/num-codex/odm2fhir/issues/16 in this regard.

CC: @noemide

**Comment by holger-stenzhorn** [comment]
@makampf You are absolutely right that it is currently missing. But what value would you actually use for `system`? If I am not mistaken it would need to reflect the actual location where the patient data was entered, so something like `"https://www.my-university-hospital.de/fhir/CodeSystem/patient-numbers"`.

**Comment by makampf** [comment]
Yes exactly. In Erlangen we currently use ENV variables to set sth like
```
patientId: "https://fhir.diz.uk-erlangen.de/NamingSystem/patientId"
```
but in my oppinion any value would be better than nothing ;)

@noemide any idea?

**Comment by holger-stenzhorn** [comment]
@makampf So I got that right... :-) The solution to provide a runtime parameter/argument to `ODM2FHIR` to set the `system` is probably the easiest and smartest one as I currently do not see how REDCap/DIS could provide that information without fiddling around.
