### ISSUE TITLE
FhirBundleToFileWriter: Failed to write bundle to file

### ISSUE THREAD

**Issue by cerbelding** [num-codex/odm2fhir#3]
## ℹ️ *new Issue from Issue #2's comments*  ℹ️ 
**Original message from @mia-wis**
> Hello,
> I am testing the ODM2FHIR Converter on a test dataset from our REDCap instance. Using the data dictionary from the 13.11.2020 and version 0.0.2-alpha-SNAPSHOT, I had a similar error to @noemide but different cause:
> `Caused by: java.lang.IllegalArgumentException: theMonth must be between 0 and 11`
> Once I changed the month from 12. to 11. this error did not occur again. I think the "allowable" month range should be corrected? 
> It seems the issue with empty values (value ="") is corrected, as my dataset had missing values but did not through the same error.
>
> However, the FHIR resource was created but not written to a file:
> ```
> 2020-12-07 14:05:29.571  INFO 1 --- [           main] ca.uhn.fhir.context.FhirContext          : Creating new FHIR context for FHIR version [R4]
> 2020-12-07 14:05:30.865  WARN 1 --- [           main] ca.uhn.fhir.parser.LenientErrorHandler   : Resource is missing required element: value
> 2020-12-07 14:05:30.973 ERROR 1 --- [           main] d.d.u.o.f.w.FhirBundleToFileWriter       : Failed to write bundle to file
> ```
> I'm not sure what the missing "value" is... Any ideas?
> [FHIRResNotSaved.](https://github.com/num-codex/odm2fhir/files/5653238/FHIRResNotSaved.txt)
> See the complete response attached.
>
> Thanks in advance!

**Comment by cerbelding** [comment]
## recent comments 
**from @cerbelding**,  07.12.2020, 15:30 MEZ
> Dear @mia-wis,
> thanks for your Issue
> I will take a look,  and come back to you asap.

**from @cerbelding**,  07.12.2020, 15:50 MEZ
> Dear @mia-wis,
> i fixed the issue regarding the wring DateOfBirth-Handling. It will work within the update of the release.
>
 >> EDIT: should now work with the newest package version
>
> The warning on a missing value does not affect writing the Bundles to a file. The app only issues this warning when a FHIR-Resource containing a value (e.g. Observation or MedicationStatement) is missing this value (which would be a mandatory property)
> This will only occur if the value is (a) malformated or (b) missing and adds the Uncertainty-of-Presence-Extension to the resource. (at least for these resources which can't be completely skipped) Therefore, this would be represented as answered with unknown
> 
> Regarding your problem with file-writing, can you please paste your docker-command when running the container? This seems like the docker-container isn't allowed to write to the given directory.

**from @mia-wis**,  08.12.2020, 10:44 MEZ
> Hi @cerbelding,
> I was using docker login, then the pull and run as shown on the package page:
>
> `docker run -v /home/wis/ODM.xml:/workspace/input/ODM.xml -v /home/wis/results/:/workspace/bundle-out docker.pkg.github.com/num-codex/odm2fhir/odm2fhir:0.0.2-alpha-snapshot`
> Can I specify the permission for the container/results folder somewhere?
>
> Thanks!
> Emilia

**from @cerbelding**,  08.12.2020, 11:02 MEZ
> Dear @mia-wis,
> your docker-command looks good.
> But does the folder /home/wis/results/ already exist?
> If you haven't created this folder in advance, the docker-daemon will create a file with the same name (in order to mount it as a volume).
> The app requires a folder instead of a file, as the Bundles are written into seperate files.
> I got the same error message when testing to run the container without creating the folder in advance.
>
> * Please make sure to delete the created results/-File with rmdir results/ (yes, that's the remove directory command, but it's nevertheless a file)
> * create the folder with mkdir results/
> * run the docker-command again!


**from @mia-wis**,  08.12.2020, 11:16 MEZ
> Hi @cerbelding,
> I just tried deleted/creating the folder but still get the same error message unfortunately. 
> Thanks in advance!

**Comment by cerbelding** [comment]
Dear @mia-wis,
can you perhaps check the access permissions for this folder?  

It can be shown with `ls -dl /home/wis/results/`   

the output should be something like this:
`drwxrwxr-x 2 *USERNAME* *USERGROUP* 4096 Dez  8 10:55 /home/wis/results/`

The first part (`drwxrwxr-x`) denotes the permissions, with `d` defining the type (directory) followed by 3 triplets (**r**ead, **w**rite, e**x**ecute) for owner, group-members and others.

This permission can be set by:
`chmod u=rwx,g=rwx,o=rx /home/wis/results/`
OR
`chmod 775 /home/wis/results/`

**Comment by mia-wis** [comment]
Hi @cerbelding,

I reset the permission for the folder and the container was able to write the resources to it now. 

Thanks,

Emilia

**Comment by cerbelding** [comment]
Dear @mia-wis,
that's great. If you notice any further problems, please contact us again.

I hereby close the issue.
