### ISSUE TITLE
0.0.2-alpha-SNAPSHOT has no description

### ISSUE THREAD

**Issue by kaibutsu** [num-codex/odm2fhir#4]
**Describe the bug**
https://github.com/num-codex/odm2fhir/packages/496804 doesn't show any description or usage information.

**To Reproduce**
1. Go to https://github.com/num-codex/odm2fhir/packages/496804
2. See no description

**Expected behavior**
A clear and concise description.

**Comment by holger-stenzhorn** [comment]
Fixed!
