### ISSUE TITLE
Directly connect to REDCap using its API. 

### ISSUE THREAD

**Issue by kaibutsu** [num-codex/odm2fhir#5]
**Is your feature request related to a problem? Please describe.**
REDCap offers a nice API to access datasets (as well as the ODM export). Doing the export (semi-)manually seems unpractical to me.

**Describe the solution you'd like**
It would be nice to do something like
`docker run odm2fhir --redcap-url [REDCap URL] --redcap-api-token [REDCap API Token]`

**Describe alternatives you've considered**
Orchestrating Export and Transformation using Airflow (doable but additional overhead).

**Comment by holger-stenzhorn** [comment]
You are absolutely right with your feature request and we are actually planning to do just exactly that, i.e. to automate the process of getting the CDISC ODM data out of RedCap using the mentioned API but further also to put the transformed (FHIR) data into a FHIR server via its REST API. To properly align this with the other development work for the CODEX platform we will have a (virtual) meeting in early January. Yet, I believe that it would make quite some sense to implement (at least) the RedCap part already now as this particular code would most likely not change even in the mentioned orchestrated environment.

**Comment by cerbelding** [comment]
Solved with Release [odm2fhir:0.0.3-alpha-SNAPSHOT](https://github.com/num-codex/odm2fhir/packages/496804)
