### ISSUE TITLE
NullPointerExeption at ImmunizationStatus

### ISSUE THREAD

**Issue by kaibutsu** [num-codex/odm2fhir#6]
**Describe the bug**
When running  odm2fhir:0.0.2-alpha-snapshot with an export of the newest Data Dictionary (NUM_GECCO_REDCap_Dictionary_2020-12-11.csv) the application quits with an NullPointerException at ImmunizationStatus.

**To Reproduce**
1. Try to convert the attached xml (rename to xml)
[GECCO_CDISC_ODM_2020-12-17_0847.xml.txt](https://github.com/num-codex/odm2fhir/files/5707761/GECCO_CDISC_ODM_2020-12-17_0847.xml.txt)

**Expected Behavior**
Error handling.

**Screenshots**
See [output.txt](https://github.com/num-codex/odm2fhir/files/5707767/output.txt)

**Desktop (please complete the following information):**
 - OS: MacOS Big Sur 11.1
 - Docker version 20.10.0, build 7287ab3

**Comment by cerbelding** [comment]
Dear @kaibutsu,
thank you for your issue.  
This error is already known and also already fixed during the implementation of the REDCap-API feature.

The new and fixed version will be published soon.

**Comment by cerbelding** [comment]
Solved with Release [odm2fhir:0.0.3-alpha-SNAPSHOT](https://github.com/num-codex/odm2fhir/packages/496804)
